This notebook contains preprocessing pipeline for the raw dataset (non missing) (python 3.9.18)

Libraries:
• tensorflow 2.15.0
• keras 2.15.0
• scikit-learn 1.3.0
• matplotlib 3.7.1

In [3]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('..')
from utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
DATASET_PATH = '../dataset'

### Preprocessing Pipeline on Raw Dataset

Load and time resolution preprocessing

In [5]:
# Load dataset
dataset = pd_import(f'{DATASET_PATH}/household_power_consumption_1_0_no_missing.csv')

In [4]:
# Make time resolution
time_resolutions = ['H'] #'30T',  'W', 'M', 'D', '1T', '4H']

for time_resolution in time_resolutions:
    dataset_resampled = dataset.resample(time_resolution).mean()
    
    # export dataset
    dataset_resampled.to_csv(f'{DATASET_PATH}/household_power_consumption_{time_resolution}.csv')

In [6]:
dataset = pd_import(f'{DATASET_PATH}/household_power_consumption_H.csv')

In [4]:
dataset_norm = scaler(dataset=dataset)

Make sequence dataset

In [5]:
# Make sequence dataset
dataset_sequence = create_sequences(dataset, 'Global_active_power', 10)
dataset_norm_sequence = create_sequences(dataset_norm, 'Global_active_power', 10)

Discretize Y (ground truth)

In [6]:
peak_label_y = np.array(generate_peak_label(dataset_sequence=dataset_sequence))

finished generating peak labels..
peak_labels == dataset_sequence


Discretize X

In [7]:
# Generate cumulative demined sequence
_, dataset_cdemined_sequence = generate_cumulative_demined_sequence(dataset_sequence=dataset_sequence)

# cluster label
col_cluster_labels = cluster_cumulative_seqs(dataset_cdemined_sequence)

# generate dataset sequence with cluster information
dataset_sequence_cluster = generate_dataset_sequence_cluster(dataset_sequence=dataset_norm_sequence, col_cluster_labels=col_cluster_labels)

c:\Users\sclab\Documents\Lab\General XAI Bayesian Network\Projects\bayesian-xai\src\preprocessing\..\utils.py:164: RuntimeWarning: invalid value encountered in scalar divide
  normalized_data = [x / total_de_minned for x in de_minned_data]


[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
34579
[0.55381179 0.35354184 0.76373749]
[0.35354184 0.55381179 0.76373749]
{0: 1, 1: 0, 2: 2}
34579
[0.67578656 0.42896484 0.55203064]
[0.42896484 0.55203064 0.67578656]
{0: 2, 1: 0, 2: 1}
34579
[0.54809956 0.668216   0.43093203]
[0.43093203 0.54809956 0.668216  ]
{0: 1, 1: 2, 2: 0}
34579
[0.55215677 0.35524945 0.76029298]
[0.35524945 0.55215677 0.76029298]
{0: 1, 1: 0, 2: 2}
34579
[0.83523327 0.01432465 0.40176741]
[0.01432465 0.40176741 0.83523327]
{0: 2, 1: 0, 2: 1}
34579
[0.55296877 0.82028577 0.23793788]
[0.23793788 0.55296877 0.82028577]
{0: 1, 1: 2, 2: 0}
34579
[0.5436395  0.75352107 0.3251839 ]
[0.3251839  0.5436395  0.75352107]
{0: 1, 1: 2, 2: 0}
34579
[0.33419096 0.79074458 0.55169754]
[0.33419096 0.55169754 0.79074458]
{0: 0, 1: 2, 2: 1}


In [8]:
dataset_sequence_cluster[0][0]

Global_active_power  Global_reactive_power   Voltage  \
datetime                                                                    
2006-12-16 17:00:00             0.636816               0.295738  0.337945   
2006-12-16 18:00:00             0.545045               0.103358  0.335501   
2006-12-16 19:00:00             0.509006               0.110073  0.283802   
2006-12-16 20:00:00             0.488550               0.096987  0.315987   
2006-12-16 21:00:00             0.455597               0.099010  0.434417   
2006-12-16 22:00:00             0.322555               0.072536  0.495847   
2006-12-16 23:00:00             0.301032               0.092251  0.567188   
2006-12-17 00:00:00             0.273201               0.132286  0.580314   
2006-12-17 01:00:00             0.501108               0.176840  0.560615   
2006-12-17 02:00:00             0.227338               0.101033  0.766631   

                     Global_intensity  Sub_metering_1  Sub_metering_2  \
datetime                                                                
2006-12-16 17:00:00          0.631157             0.0        0.011366   
2006-12-16 18:00:00          0.541487             0.0        0.144652   
2006-12-16 19:00:00          0.502152             0.0        0.030869   
2006-12-16 20:00:00          0.481110             0.0        0.000000   
2006-12-16 21:00:00          0.449904             0.0        0.008973   
2006-12-16 22:00:00          0.323529             0.0        0.002872   
2006-12-16 23:00:00          0.301052             0.0        0.001795   
2006-12-17 00:00:00          0.273434             0.0        0.010050   
2006-12-17 01:00:00          0.492946             0.0        0.543431   
2006-12-17 02:00:00          0.228360             0.0        0.012204   

                     Sub_metering_3  sub_metering_4  
datetime                                             
2006-12-16 17:00:00        0.782418        0.813346  
2006-12-16 18:00:00        0.782676        0.560591  
2006-12-16 19:00:00        0.774169        0.585814  
2006-12-16 20:00:00        0.778809        0.572244  
2006-12-16 21:00:00        0.798917        0.503143  
2006-12-16 22:00:00        0.205723        0.484145  
2006-12-16 23:00:00        0.000000        0.518411  
2006-12-17 00:00:00        0.000000        0.465323  
2006-12-17 01:00:00        0.000000        0.460315  
2006-12-17 02:00:00        0.000000        0.386215

Save

In [9]:
# peak_label_old = np.load(f'{DATASET_PATH}/preprocessed/H/peak_labels_1H_10W.npy')
# peak label y 
np.save(f'{DATASET_PATH}/peak_labels_1H_10W.npy', peak_label_y)

# sequence dataset with corresponding cluster and ground truth Y (cont.)
with open(f'{DATASET_PATH}/dataset_sequence_cluster_1H_10W.pkl', 'wb') as f:
    pkl.dump(dataset_sequence_cluster, f)
# dataset_sequence_cluster